packages:
  - bench
  - docs
  - playground
  - interactive
  - packages/**
  - test/fixtures/*
  - examples/vue-cli4
  - examples/vue-cli5
catalog:
  '@ampproject/remapping': ^2.3.0
  '@antfu/eslint-config': ^2.27.1
  '@antfu/ni': ^0.22.4
  '@antfu/utils': ^0.7.10
  '@babel/core': ^7.25.2
  '@babel/plugin-syntax-jsx': ^7.24.7
  '@babel/preset-typescript': ^7.24.7
  '@codemirror/lang-css': ^6.2.1
  '@codemirror/lang-html': ^6.4.9
  '@codemirror/lang-javascript': ^6.2.2
  '@codemirror/lang-xml': ^6.1.0
  '@csstools/normalize.css': ^12.1.1
  '@iconify-json/carbon': ^1.1.37
  '@iconify-json/iconoir': ^1.1.46
  '@iconify-json/la': ^1.1.9
  '@iconify-json/logos': ^1.1.44
  '@iconify-json/mdi': ^1.1.68
  '@iconify-json/ph': ^1.1.14
  '@iconify-json/ri': ^1.1.22
  '@iconify-json/tabler': ^1.1.120
  '@iconify-json/teenyicons': ^1.1.10
  '@iconify-json/twemoji': ^1.1.16
  '@iconify-json/uim': ^1.1.10
  '@iconify-json/vscode-icons': ^1.1.37
  '@iconify/json': ^2.2.241
  '@iconify/types': ^2.0.0
  '@iconify/utils': ^2.1.32
  '@nuxt/devtools': ^1.3.14
  '@nuxt/kit': ^3.13.0
  '@nuxt/schema': ^3.13.0
  '@rollup/pluginutils': ^5.1.0
  '@shikijs/markdown-it': ^1.14.1
  '@shikijs/vitepress-twoslash': ^1.14.1
  '@sveltejs/kit': ^2.5.24
  '@types/connect': ^3.4.38
  '@types/css-tree': ^2.3.8
  '@types/fs-extra': ^11.0.4
  '@types/js-yaml': ^4.0.9
  '@types/markdown-it-link-attributes': ^3.0.5
  '@types/node': ^22.5.0
  '@types/prettier': ^2.7.3
  '@types/pug': ^2.0.10
  '@types/react': ^18.3.4
  '@types/webpack': ^5.28.5
  '@types/webpack-sources': ^3.2.3
  '@types/ws': ^8.5.12
  '@typescript-eslint/utils': ^8.2.0
  '@vitejs/plugin-legacy': ^5.4.2
  '@vitejs/plugin-vue': ^5.1.2
  '@vitest/ui': ^2.0.5
  '@vue/reactivity': ^3.4.38
  '@vueuse/core': ^11.0.1
  '@vueuse/math': ^11.0.1
  '@vueuse/nuxt': ^11.0.1
  astro: ^4.14.5
  autoprefixer: ^10.4.20
  brotli-size: ^4.0.0
  bumpp: ^9.5.2
  cac: ^6.7.14
  chokidar: ^3.6.0
  codemirror: ^6.0.1
  codemirror-theme-vars: ^0.1.2
  colorette: ^2.0.20
  consola: ^3.2.3
  css-tree: ^2.3.1
  eslint: ^9.9.1
  eslint-plugin-antfu: ^2.3.6
  eslint-vitest-rule-tester: ^0.6.1
  esno: ^4.7.0
  execa: ^9.3.1
  find-up: ^6.3.0
  floating-vue: 2.0.0-beta.24
  fs-extra: ^11.2.0
  fuse.js: ^7.0.0
  fzf: ^0.5.2
  gzip-size: ^6.0.0
  jiti: ^1.21.6
  js-yaml: ^4.1.0
  jsdom: ^24.1.1
  knitwork: ^1.1.0
  lint-staged: ^15.2.9
  local-pkg: ^0.5.0
  lru-cache: ^10.4.3
  lz-string: ^1.5.0
  magic-string: ^0.30.11
  markdown-it-link-attributes: ^4.0.1
  msw: 1.0.1
  nuxt: ^3.13.0
  nuxt-tsconfig-stub: ^0.0.2
  ofetch: ^1.3.4
  p-limit: ^6.1.0
  pathe: ^1.1.2
  perfect-debounce: ^1.0.0
  pnpm: 8.9.2
  postcss: ^8.4.41
  postcss-nested: ^6.2.0
  prettier: ^2.8.8
  prettier-plugin-svelte: ^2.10.1
  pug: ^3.0.3
  react: ^18.3.1
  rimraf: ^6.0.1
  rollup: ^4.21.0
  sanitize.css: ^13.0.0
  semver: ^7.6.3
  shiki: ^1.14.1
  simple-git: ^3.25.0
  simple-git-hooks: ^2.11.1
  sirv: ^2.0.4
  splitpanes: ^3.1.5
  std-env: ^3.7.0
  svelte: ^4.2.19
  synckit: ^0.9.1
  tailwindcss: ^3.4.10
  taze: ^0.16.6
  terser: ^5.31.6
  theme-vitesse: ^0.8.3
  tinyglobby: ^0.2.5
  tsup: ^8.2.4
  typescript: ^5.5.4
  unbuild: ^2.0.0
  unconfig: ^0.5.5
  unplugin: ^1.12.2
  unplugin-auto-import: ^0.18.2
  unplugin-vue-components: ^0.27.4
  unplugin-vue-markdown: ^0.26.2
  vite: ^5.4.2
  vite-plugin-inspect: ^0.8.7
  vite-plugin-pages: ^0.32.3
  vite-plugin-windicss: ^1.9.3
  vitepress: ^1.3.3
  vitepress-plugin-group-icons: ^1.0.3
  vitest: ^2.0.5
  vue: ^3.4.38
  vue-eslint-parser: ^9.4.3
  vue-router: ^4.4.3
  vue-virtual-scroller: 2.0.0-beta.8
  webpack: ^5.94.0
  webpack-sources: ^3.2.3
  windicss: ^3.5.6
